name: Deploy package
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  publish:
    environment: regulad-releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.m2
          key: ahCache-${{ hashFiles('./pom.xml') }}
      - name: Set up maven repository
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
          server-id: regulad-releases
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn package deploy
        env:
          MAVEN_USERNAME: ${{ secrets.SERVER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: AdvancementHunt
          path: target/*.jar
  # Maybe a step that installs javadocs to the gh-pages branch?
