# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and Artifact

on:
  push:
    branches: [ rewrite ]
  pull_request:
    branches: [ rewrite ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2.1.4
      with:
        path: |
          ~/.m2
        key: ahCache-${{ hashFiles('./pom.xml') }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: adopt
    - name: Build with Maven
      run: mvn package
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: AdvancementHunt
        path: target/*.jar 
