name: Matchmaker CI

on:
  create:
  push:
    tags:
      - '*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.m2
          key: mmCache-${{ hashFiles('./pom.xml') }}
      - name: Set up JDK 1.16
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt
      - name: Build with Maven
        run: mvn package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/')
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: target/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
